### PR TITLE
Chat

### PR DESCRIPTION
**Pull request by agomez314**
Creates chat room

### CODE REVIEW

**Comment by 17kpatrick** [comment]
I'm getting the following error in console when entering my username, trapping me in a loop of being asked for the username:

`Failed to load resource: the server responded with a status of 404 (Not Found)
index.html:71 Uncaught ReferenceError: io is not defined
    at index.html:71
jquery-3.3.1.min.js:2 jQuery.Deferred exception: io is not defined ReferenceError: io is not defined
    at HTMLDocument.<anonymous> (http://localhost:63342/rainbow-game/public/js/chat.js:33:18)
    at l (http://localhost:63342/rainbow-game/public/js/jquery-3.3.1.min.js:2:29375)
    at c (http://localhost:63342/rainbow-game/public/js/jquery-3.3.1.min.js:2:29677) undefined
w.Deferred.exceptionHook @ jquery-3.3.1.min.js:2
jquery-3.3.1.min.js:2 Uncaught ReferenceError: io is not defined
    at HTMLDocument.<anonymous> (chat.js:33)
    at l (jquery-3.3.1.min.js:2)
    at c (jquery-3.3.1.min.js:2)`

I've looked and I don't see the /socket.io/socket.io.js that is defined in index.html. Is this something which did not get pushed?

**Comment by agomez314** [comment]
Did you run npm install

Alejandro Gomez

**Comment by 17kpatrick** [comment]
Yes, I ran npm install which created the node_modules folder that has a socket.io folder and a socket.js file within that, but that is a different location and file name than what the html script source says, so I wasn't sure if that was the same file but installed differently for me. 

Is npm install supposed to install to the node_modules folder?

**Comment by agomez314** [comment]
Yes that’s what It does. It installs all dependencies. Are you starting the server with node app.js?

Alejandro Gomez

**Comment by 17kpatrick** [comment]
I wasn't starting it with node app.js, that was the problem. Thanks!

**Comment by 17kpatrick** [comment]
This is now merged with main, but there is an issue which I think is related to the animations. Each token can only move up/down once and then left/right once. After this they no longer are able to move again.

**Pull request merged**
