### PR TITLE
player token container implementation; set container implementation

### PR DESCRIPTION
**Pull request by matthewtelayman**

### CODE REVIEW

**Comment by 17kpatrick** [comment]
It seems as though something in this update made it so that certain tokens on the board (especially near the middle) can no longer be selected. If you click around you should also be able to see that some tokens cannot be selected anymore and some have a hard time being selected. If I had to guess it is likely something to do with the tile coloring. I can look into this tomorrow morning, unless you have any ideas.

**Comment by 17kpatrick** [comment]
Actually it looks like the tile containers are just covering up certain tiles.

**Comment by 17kpatrick** [comment]
Alright that was an easy fix, the token container no longer covers the tokens on the left side of the board.

**Comment by matthewtelayman** [comment]
May have to do the same on player 4 token container

**Comment by 17kpatrick** [comment]
Yeah, player 4 covers the chat feed. I'll do it to that as well to be safe.

**Pull request merged**
